In [29]:
w1 , w2 ,w3 = 0.3,0.2,0.5

In [30]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [31]:
weights = [w1, w2, w3]

In [32]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [33]:
print (crop_yield(kanto, weights),
crop_yield(johto, weights),
crop_yield(hoenn, weights),
crop_yield(sinnoh, weights),
crop_yield(unova, weights))

56.8 76.9 81.9 57.699999999999996 74.9


In [34]:
import numpy as np 

In [35]:
kanto = np.array([73, 67, 43])

In [36]:
weights = np.array([w1,w2,w3])

In [37]:
type (kanto)

numpy.ndarray

In [38]:
type (weights)

numpy.ndarray

In [39]:
#now computing the dot product of two array using np.dot()

In [40]:
np.dot(kanto,weights)

56.8

In [41]:
#this can be also callcuted by low level operation supported by numpy arrays 

In [42]:
(kanto*weights).sum()

56.8

In [43]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [44]:
arr1 * arr2

array([ 4, 10, 18])

In [45]:
arr2.sum()

15

In [46]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [47]:
arr1

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [48]:
arr1_np

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [49]:
arr2

[1000000,
 1000001,
 1000002,
 1000003,
 1000004,
 1000005,
 1000006,
 1000007,
 1000008,
 1000009,
 1000010,
 1000011,
 1000012,
 1000013,
 1000014,
 1000015,
 1000016,
 1000017,
 1000018,
 1000019,
 1000020,
 1000021,
 1000022,
 1000023,
 1000024,
 1000025,
 1000026,
 1000027,
 1000028,
 1000029,
 1000030,
 1000031,
 1000032,
 1000033,
 1000034,
 1000035,
 1000036,
 1000037,
 1000038,
 1000039,
 1000040,
 1000041,
 1000042,
 1000043,
 1000044,
 1000045,
 1000046,
 1000047,
 1000048,
 1000049,
 1000050,
 1000051,
 1000052,
 1000053,
 1000054,
 1000055,
 1000056,
 1000057,
 1000058,
 1000059,
 1000060,
 1000061,
 1000062,
 1000063,
 1000064,
 1000065,
 1000066,
 1000067,
 1000068,
 1000069,
 1000070,
 1000071,
 1000072,
 1000073,
 1000074,
 1000075,
 1000076,
 1000077,
 1000078,
 1000079,
 1000080,
 1000081,
 1000082,
 1000083,
 1000084,
 1000085,
 1000086,
 1000087,
 1000088,
 1000089,
 1000090,
 1000091,
 1000092,
 1000093,
 1000094,
 1000095,
 1000096,
 1000097,
 1000098,
 1000099,


In [50]:
arr2_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [58]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 234 ms
Wall time: 295 ms


833332333333500000

In [59]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 2.52 ms


-1942957984

In [60]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [62]:
type(climate_data)

numpy.ndarray

In [64]:
climate_data.shape

(5, 3)

In [66]:
type(weights)

numpy.ndarray

In [67]:
weights.shape

(3,)

In [ ]:
#using matmul to multiply two matrix or also done by using @  

In [68]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [69]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [70]:
#now reading the data using csv file  : 

In [71]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x22ec7e872d0>)

In [72]:
climate_data  = np.genfromtxt('climate.txt',delimiter=',', skip_header=1)

In [73]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [74]:
climate_data.shape

(10000, 3)

In [75]:
yields = climate_data @ weights 

In [76]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [77]:
yields.shape

(10000,)

In [79]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [81]:
climate_results 

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [82]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [83]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [84]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [85]:
arr2 + 4

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13,  5,  6,  7]])

In [86]:
arr3 - arr2 

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [87]:
arr2 / 2 

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [89]:
(arr2 - 1 )%4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 0, 1, 2]], dtype=int32)

In [90]:
##numpy operations 

In [91]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [92]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# : Flatten a multi-dimensional array into a 1D array
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
import numpy as np

# Creating the example array
arr = np.arange(1, 10)
print("Original array:", arr)


Original array: [1 2 3 4 5 6 7 8 9]


In [114]:
# Creating arrays filled with zeros and ones
zeros = np.zeros(9)
ones = np.ones(9)
linspace_arr = np.linspace(1, 9, 9)

print("Array of zeros:", zeros)
print("Array of ones:", ones)
print("Linearly spaced array:", linspace_arr)


Array of zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Linearly spaced array: [1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [115]:
linspace_arr = np.linspace(1, 9, 10001)
print("Linearly spaced array:", linspace_arr)

Linearly spaced array: [1.     1.0008 1.0016 ... 8.9984 8.9992 9.    ]


In [124]:
# Reshape the array to 3x3
reshaped_arr = arr.reshape(3, 3)
print("Reshaped array (3x3):", reshaped_arr)

# Flatten the reshaped array
flattened_arr = reshaped_arr.flatten()
print("Flattened array:", flattened_arr)

# Concatenate arrays
concatenated_arr = np.concatenate((arr, arr))
print("Concatenated array:", concatenated_arr)

# Stack arrays vertically and horizontally
vstacked_arr = np.vstack((arr, arr,arr))
hstacked_arr = np.hstack((arr, arr,arr))
print("Vertically stacked array:\n", vstacked_arr)
print("Horizontally stacked array:", hstacked_arr)

# Split array into 3 sub-arrays
split_arr = np.split(arr, 1)
print("Split array into 3 sub-arrays:", split_arr)


Reshaped array (3x3): [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array: [1 2 3 4 5 6 7 8 9]
Concatenated array: [1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
Vertically stacked array:
 [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
Horizontally stacked array: [1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]
Split array into 3 sub-arrays: [array([1, 2, 3, 4, 5, 6, 7, 8, 9])]


In [125]:
# Element-wise addition, subtraction, multiplication, division
add_arr = np.add(arr, 2)
sub_arr = np.subtract(arr, 2)
mul_arr = np.multiply(arr, 2)
div_arr = np.divide(arr, 2)

print("Addition:", add_arr)
print("Subtraction:", sub_arr)
print("Multiplication:", mul_arr)
print("Division:", div_arr)

# Dot product (with itself reshaped as a 3x3 matrix)
dot_product = np.dot(reshaped_arr, reshaped_arr)
print("Dot product:\n", dot_product)

# Square root, exponential, logarithm
sqrt_arr = np.sqrt(arr)
exp_arr = np.exp(arr)
log_arr = np.log(arr)

print("Square root:", sqrt_arr)
print("Exponential:", exp_arr)
print("Logarithm:", log_arr)

# Sum, mean, standard deviation, variance, min, max
sum_arr = np.sum(arr)
mean_arr = np.mean(arr)
std_arr = np.std(arr)
var_arr = np.var(arr)
min_arr = np.min(arr)
max_arr = np.max(arr)

print("Sum:", sum_arr)
print("Mean:", mean_arr)
print("Standard deviation:", std_arr)
print("Variance:", var_arr)
print("Min:", min_arr)
print("Max:", max_arr)


Addition: [ 3  4  5  6  7  8  9 10 11]
Subtraction: [-1  0  1  2  3  4  5  6  7]
Multiplication: [ 2  4  6  8 10 12 14 16 18]
Division: [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Dot product:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
Exponential: [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
Sum: 45
Mean: 5.0
Standard deviation: 2.581988897471611
Variance: 6.666666666666667
Min: 1
Max: 9


In [126]:
# Median, percentile
median_arr = np.median(arr)
percentile_arr = np.percentile(arr, 50)

print("Median:", median_arr)
print("50th percentile:", percentile_arr)

# Correlation coefficient matrix, covariance matrix
corrcoef_arr = np.corrcoef(reshaped_arr)
cov_arr = np.cov(reshaped_arr)

print("Correlation coefficient matrix:\n", corrcoef_arr)
print("Covariance matrix:\n", cov_arr)


Median: 5.0
50th percentile: 5.0
Correlation coefficient matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Covariance matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [127]:
# Inverse, determinant, eigenvalues and eigenvectors
# For these operations, we need a square matrix, so we use reshaped_arr (3x3)
inverse_arr = np.linalg.inv(reshaped_arr)
det_arr = np.linalg.det(reshaped_arr)
eigvals, eigvecs = np.linalg.eig(reshaped_arr)
u, s, vh = np.linalg.svd(reshaped_arr)
sol = np.linalg.solve(reshaped_arr, [1, 2, 3])

print("Inverse of matrix:\n", inverse_arr)
print("Determinant of matrix:", det_arr)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)
print("Singular Value Decomposition (U, S, V^H):\n", u, s, vh)
print("Solution of linear matrix equation:", sol)


Inverse of matrix:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
Determinant of matrix: -9.51619735392994e-16
Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
Singular Value Decomposition (U, S, V^H):
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]] [1.68481034e+01 1.06836951e+00 3.33475287e-16] [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Solution of linear matrix equation: [-0.23333333  0.46666667  0.1       ]


In [128]:
# Random numbers uniformly distributed, normally distributed, random integers
rand_arr = np.random.rand(9)
randn_arr = np.random.randn(9)
randint_arr = np.random.randint(1, 10, 9)

print("Random numbers (uniform):", rand_arr)
print("Random numbers (normal):", randn_arr)
print("Random integers:", randint_arr)


Random numbers (uniform): [0.44498443 0.96268743 0.87217552 0.13737418 0.91084418 0.88935703
 0.6091946  0.74367259 0.06514348]
Random numbers (normal): [-1.0445696   0.69144511  0.20775281  0.89762623  1.12622441  0.17437404
 -0.07932058 -1.1239302  -0.32344313]
Random integers: [8 7 2 9 7 8 2 9 8]


In [129]:
import numpy as np

# Creating arrays
empty_arr = np.empty((3, 3))
eye_arr = np.eye(3)
full_arr = np.full((3, 3), 7)
print("Empty array:\n", empty_arr)
print("Identity matrix:\n", eye_arr)
print("Full array with sevens:\n", full_arr)

# Array attributes and information
arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print("Array shape:", arr.shape)
print("Array size:", arr.size)
print("Array dtype:", arr.dtype)

# Sorting and searching
sorted_arr = np.sort(arr, axis=1)
indices_sorted = np.argsort(arr, axis=1)
print("Sorted array:\n", sorted_arr)
print("Indices that would sort the array:\n", indices_sorted)

# Set operations
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
unique_arr = np.unique(arr1)
intersect_arr = np.intersect1d(arr1, arr2)
union_arr = np.union1d(arr1, arr2)
setdiff_arr = np.setdiff1d(arr1, arr2)
print("Unique elements:", unique_arr)
print("Intersection:", intersect_arr)
print("Union:", union_arr)
print("Set difference:", setdiff_arr)

# Broadcasting and other miscellaneous operations
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
broadcasted_sum = a + b
print("Broadcasted sum:\n", broadcasted_sum)

# Transpose and flattening
transposed_arr = np.transpose(arr)
raveled_arr = np.ravel(arr)
print("Transposed array:\n", transposed_arr)
print("Flattened array:", raveled_arr)

# Clipping values
clipped_arr = np.clip(arr, 2, 5)
print("Clipped array:", clipped_arr)


Empty array:
 [[1.0445696  0.69144511 0.20775281]
 [0.89762623 1.12622441 0.17437404]
 [0.07932058 1.1239302  0.32344313]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Full array with sevens:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Array shape: (2, 3)
Array size: 6
Array dtype: int32
Sorted array:
 [[1 2 3]
 [4 5 6]]
Indices that would sort the array:
 [[0 1 2]
 [0 1 2]]
Unique elements: [1 2 3 4]
Intersection: [3 4]
Union: [1 2 3 4 5 6]
Set difference: [1 2]
Broadcasted sum:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Flattened array: [1 2 3 4 5 6]
Clipped array: [[2 2 3]
 [4 5 5]]
